run:
	java QuickSort.java  "../CSV/data/100.csv" "100"

measure:
	sudo modprobe msr
	sudo ../../RAPL/main "java QuickSort.java "../CSV/100.csv" "100" " Javaq quicksort1
	sudo ../../RAPL/main "java QuickSort.java "../CSV/200.csv" "200" " Javaq quicksort2
	sudo ../../RAPL/main "java QuickSort.java "../CSV/300.csv" "300" " Javaq quicksort3
	sudo ../../RAPL/main "java QuickSort.java "../CSV/400.csv" "400" " Javaq quicksort4
	sudo ../../RAPL/main "java QuickSort.java "../CSV/500.csv" "500" " Javaq quicksort5
	sudo ../../RAPL/main "java QuickSort.java "../CSV/600.csv" "600" " Javaq quicksort6
	sudo ../../RAPL/main "java QuickSort.java "../CSV/700.csv" "700" " Javaq quicksort7
	sudo ../../RAPL/main "java QuickSort.java "../CSV/800.csv" "800" " Javaq quicksort8
	sudo ../../RAPL/main "java QuickSort.java "../CSV/900.csv" "900" " Javaq quicksort9
	sudo ../../RAPL/main "java QuickSort.java "../CSV/1000.csv" "1000" " Javaq quicksort10

measureExtreme: 
	sudo modprobe msr
	sudo ../../RAPL/main "java QuickSort.java "../CSV/10000.csv" "10000" " JavaqE quicksort1
	sudo ../../RAPL/main "java QuickSort.java "../CSV/20000.csv" "20000" " JavaqE quicksort2
	sudo ../../RAPL/main "java QuickSort.java "../CSV/30000.csv" "30000" " JavaqE quicksort3
	sudo ../../RAPL/main "java QuickSort.java "../CSV/40000.csv" "40000" " JavaqE quicksort4
	sudo ../../RAPL/main "java QuickSort.java "../CSV/50000.csv" "50000" " JavaqE quicksort5
	sudo ../../RAPL/main "java QuickSort.java "../CSV/60000.csv" "60000" " JavaqE quicksort6
	sudo ../../RAPL/main "java QuickSort.java "../CSV/70000.csv" "70000" " JavaqE quicksort7
	sudo ../../RAPL/main "java QuickSort.java "../CSV/80000.csv" "80000" " JavaqE quicksort8
	sudo ../../RAPL/main "java QuickSort.java "../CSV/90000.csv" "90000" " JavaqE quicksort9
	sudo ../../RAPL/main "java QuickSort.java "../CSV/100000.csv" "100000" " JavaqE quicksort10

