dataPrelim:
	java makeData.java 10000
	java makeData.java 20000
	java makeData.java 30000
	java makeData.java 40000
	java makeData.java 50000
	java makeData.java 60000
	java makeData.java 70000
	java makeData.java 80000
	java makeData.java 90000
	java makeData.java 100000

data:
	java makeData.java 25000
	java makeData.java 50000
	java makeData.java 75000
	java makeData.java 100000
	java makeData.java 200000
	java makeData.java 300000
	java makeData.java 400000
	java makeData.java 500000
	java makeData.java 600000
	java makeData.java 700000
	java makeData.java 800000
	java makeData.java 900000
	java makeData.java 1000000

