run:
	java bubblesort.java

testRAPL:
	sudo modprobe msr
	sudo ../../RAPL/main "java bubblesort.java "../CSV/data/100.csv" "100" " Java bubblesort100

measure:
	sudo modprobe msr
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/10000.csv" "10000" " JavaqE bubblesort10000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/20000.csv" "20000" " JavaqE bubblesort20000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/30000.csv" "30000" " JavaqE bubblesort30000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/40000.csv" "40000" " JavaqE bubblesort40000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/50000.csv" "50000" " JavaqE bubblesort50000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/60000.csv" "60000" " JavaqE bubblesort60000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/70000.csv" "70000" " JavaqE bubblesort70000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/80000.csv" "80000" " JavaqE bubblesort80000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/90000.csv" "90000" " JavaqE bubblesort90000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/100000.csv" "100000" " JavaqE bubblesort100000