run:
	java bubblesort.java

testRAPL:
	sudo modprobe msr
	sudo ../../RAPL/main "java bubblesort.java "../CSV/data/100.csv" "100" " Java bubblesort100

measure:
	sudo modprobe msr
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/25000.csv" "25000" " JavaqE bubblesort25000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/50000.csv" "50000" " JavaqE bubblesort50000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/75000.csv" "75000" " JavaqE bubblesort75000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/100000.csv" "100000" " JavaqE bubblesort100000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/100000.csv" "200000" " JavaqE bubblesort200000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/100000.csv" "300000" " JavaqE bubblesort300000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/100000.csv" "400000" " JavaqE bubblesort400000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/500000.csv" "500000" " JavaqE bubblesort500000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/600000.csv" "600000" " JavaqE bubblesort600000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/700000.csv" "700000" " JavaqE bubblesort700000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/800000.csv" "800000" " JavaqE bubblesort800000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/900000.csv" "900000" " JavaqE bubblesort900000
	sudo ../../RAPL/main "java QuickSort.java "../CSV/data/1000000.csv" "1000000" " JavaqE bubblesort1000000

