data:
	java makeData.java 100
	java makeData.java 200
	java makeData.java 300
	java makeData.java 400
	java makeData.java 500
	java makeData.java 600
	java makeData.java 700
	java makeData.java 800
	java makeData.java 900
	java makeData.java 1000


dataExtreme:
	java makeData.java 10000
	java makeData.java 20000
	java makeData.java 30000
	java makeData.java 40000
	java makeData.java 50000
	java makeData.java 60000
	java makeData.java 70000
	java makeData.java 80000
	java makeData.java 90000
	java makeData.java 100000
