run:
	java JavaSort.java "../CSV/data/100.csv" 100

measure:
	sudo modprobe msr
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/100.csv" "100" " JavaSort JavaSort1
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/200.csv" "200" " JavaSort JavaSort2
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/300.csv" "300" " JavaSort JavaSort3
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/400.csv" "400" " JavaSort JavaSort4
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/500.csv" "500" " JavaSort JavaSort5
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/600.csv" "600" " JavaSort JavaSort6
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/700.csv" "700" " JavaSort JavaSort7
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/800.csv" "800" " JavaSort JavaSort8
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/900.csv" "900" " JavaSort JavaSort9
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/1000.csv" "1000" " JavaSort JavaSort10
	
measureExtreme:
	sudo modprobe msr
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/10000.csv" "10000" " JavaSortE JavaSort1
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/20000.csv" "20000" " JavaSortE JavaSort2
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/30000.csv" "30000" " JavaSortE JavaSort3
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/40000.csv" "40000" " JavaSortE JavaSort4
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/50000.csv" "50000" " JavaSortE JavaSort5
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/60000.csv" "60000" " JavaSortE JavaSort6
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/70000.csv" "70000" " JavaSortE JavaSort7
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/80000.csv" "80000" " JavaSortE JavaSort8
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/90000.csv" "90000" " JavaSortE JavaSort9
	sudo ../../RAPL/main "java JavaSort.java " ../CSV/data/100000.csv" "100000" " JavaSortE JavaSort10	