run:
	sudo java countingSort.java "arrays/100.csv" "100"


measure:
	sudo modprobe msr
	sudo ../../RAPL/main "java countingSort.java "arrays/25000.csv" "25000" " count25k-1M countingSort25000
	sudo ../../RAPL/main "java countingSort.java "arrays/50000.csv" "50000" " count25k-1M countingSort50000
	sudo ../../RAPL/main "java countingSort.java "arrays/75000.csv" "75000" " count25k-1M countingSort75000
	sudo ../../RAPL/main "java countingSort.java "arrays/100000.csv" "100000" " count25k-1M countingSort100000
	sudo ../../RAPL/main "java countingSort.java "arrays/200000.csv" "200000" " count25k-1M countingSort200000
	sudo ../../RAPL/main "java countingSort.java "arrays/300000.csv" "300000" " count25k-1M countingSort300000
	sudo ../../RAPL/main "java countingSort.java "arrays/400000.csv" "400000" " count25k-1M countingSort400000
	sudo ../../RAPL/main "java countingSort.java "arrays/500000.csv" "500000" " count25k-1M countingSort500000
	sudo ../../RAPL/main "java countingSort.java "arrays/600000.csv" "600000" " count25k-1M countingSort600000
	sudo ../../RAPL/main "java countingSort.java "arrays/700000.csv" "700000" " count25k-1M countingSort700000
	sudo ../../RAPL/main "java countingSort.java "arrays/800000.csv" "800000" " count25k-1M countingSort800000
	sudo ../../RAPL/main "java countingSort.java "arrays/900000.csv" "900000" " count25k-1M countingSort900000
	sudo ../../RAPL/main "java countingSort.java "arrays/1000000.csv" "1000000" " count25k-1M countingSort1000000
